// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RubyElektronik.Data;

#nullable disable

namespace RubyElektronik.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250912075315_AddProductImagePath")]
    partial class AddProductImagePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RubyElektronik.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 7, 7, 53, 14, 767, DateTimeKind.Utc).AddTicks(599),
                            ProductId = 1,
                            ProductName = "Samsung 55\" 4K Smart TV",
                            Quantity = 2,
                            Status = "Completed",
                            TotalPrice = 17999.98m,
                            UnitPrice = 8999.99m,
                            UserId = 1,
                            UserName = "Ahmet Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 10, 7, 53, 14, 767, DateTimeKind.Utc).AddTicks(607),
                            ProductId = 2,
                            ProductName = "iPhone 15 Pro 128GB",
                            Quantity = 1,
                            Status = "Pending",
                            TotalPrice = 54999.99m,
                            UnitPrice = 54999.99m,
                            UserId = 2,
                            UserName = "ABC Elektronik Ltd. Şti."
                        });
                });

            modelBuilder.Entity("RubyElektronik.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Televizyon",
                            CreatedAt = new DateTime(2025, 9, 12, 7, 53, 14, 767, DateTimeKind.Utc).AddTicks(427),
                            Description = "55 inç 4K Ultra HD Smart LED TV",
                            IsActive = true,
                            Name = "Samsung 55\" 4K Smart TV",
                            Price = 8999.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Telefon",
                            CreatedAt = new DateTime(2025, 9, 12, 7, 53, 14, 767, DateTimeKind.Utc).AddTicks(430),
                            Description = "Apple iPhone 15 Pro 128GB Titanium",
                            IsActive = true,
                            Name = "iPhone 15 Pro 128GB",
                            Price = 54999.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Bilgisayar",
                            CreatedAt = new DateTime(2025, 9, 12, 7, 53, 14, 767, DateTimeKind.Utc).AddTicks(432),
                            Description = "Apple MacBook Air M2 13 inç 256GB SSD",
                            IsActive = true,
                            Name = "MacBook Air M2 13\" 256GB",
                            Price = 39999.99m
                        });
                });

            modelBuilder.Entity("RubyElektronik.Models.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ArizaAciklamasi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirmaAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrunTuru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ahmet",
                            ArizaAciklamasi = "Televizyon açılmıyor, güç düğmesine bastığımda hiçbir tepki vermiyor.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Soyad = "Yılmaz",
                            TelefonNumarasi = "+90 555 123 4567",
                            UrunTuru = "Samsung TV",
                            UserType = 0
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayşe",
                            ArizaAciklamasi = "Laptop çok ısınıyor ve fan sesi çok yüksek çıkıyor. Performans düşüklüğü yaşıyoruz.",
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirmaAdi = "ABC Şirketi",
                            IsActive = true,
                            Soyad = "Demir",
                            TelefonNumarasi = "+90 212 555 1234",
                            UrunTuru = "HP Laptop",
                            UserType = 1
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mehmet",
                            ArizaAciklamasi = "Telefonun ekranında çizikler var ve batarya çok hızlı bitiyor.",
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Soyad = "Kaya",
                            TelefonNumarasi = "+90 532 987 6543",
                            UrunTuru = "iPhone 14",
                            UserType = 0
                        });
                });

            modelBuilder.Entity("RubyElektronik.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul, Türkiye",
                            CreatedAt = new DateTime(2025, 9, 12, 7, 53, 14, 767, DateTimeKind.Utc).AddTicks(573),
                            Email = "ahmet@example.com",
                            IsActive = true,
                            Name = "Ahmet Yılmaz",
                            PhoneNumber = "+90 555 123 4567",
                            UserType = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Abdullahazam Cd. NO:28/A, Huzur Mahallesi, 34773 Ümraniye/İstanbul",
                            CompanyName = "ABC Elektronik Ltd. Şti.",
                            CreatedAt = new DateTime(2025, 9, 12, 7, 53, 14, 767, DateTimeKind.Utc).AddTicks(575),
                            Email = "info@abcelektronik.com",
                            IsActive = true,
                            Name = "ABC Elektronik Ltd. Şti.",
                            PhoneNumber = "+90 212 555 0123",
                            UserType = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Abdullahazam Cd. NO:28/A, Huzur Mahallesi, 34773 Ümraniye/İstanbul",
                            CompanyName = "Ruby Elektronik",
                            CreatedAt = new DateTime(2025, 9, 12, 7, 53, 14, 767, DateTimeKind.Utc).AddTicks(577),
                            Email = "hasanhuseyinyakut@gmail.com",
                            IsActive = true,
                            Name = "Ruby Elektronik",
                            PhoneNumber = "+90 546 944 33 88",
                            UserType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
